apiVersion: apps/v1
kind: Deployment
metadata:
  name: serveur-deployment
  labels:
    app: serveur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serveur
  template:
    metadata:
      labels:
        app: serveur
    spec:
      containers:
        - name: serveur
          image: maram172003/atelier4-serveur:TAG
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: serveur-service
spec:
  selector:
    app: serveur
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP


